channels:
  - pytorch
  - omnia
  - conda-forge
  - defaults
dependencies:
  - openmm
  - pdbfixer
  - rdkit
  - pytorch=1.7.0
  - cudatoolkit=10.1.243
  - pip
  - pip:
    - networkx
    - biopython
    - h5py
    - pot
    - wandb
